services:
  - type: web
    name: contract-management-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python run_production.py
    plan: free
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: LLAMACLOUD_API_KEY
        sync: false
      - key: ENVIRONMENT
        value: production
      - key: PORT
        value: 10000
    healthCheckPath: /health
